/* Synthetic showcase fixtures. Never substitute these for missing live API data. */
export const sampleDailyOrders = [
  18, 22, 19, 24, 21, 28, 33, 25, 29, 31, 27, 36, 34, 38, 41, 37, 44, 39, 42,
  47, 43, 50, 46, 54, 58, 53, 61, 57, 65, 68,
].map((orders, index) => {
  const date = new Date('2026-09-08T00:00:00.000Z')
  date.setDate(date.getDate() - (29 - index))
  return { date: date.toISOString().slice(0, 10), orders }
})

export const sampleImages = {
  earbuds: '/demo-earbuds.jpg',
  watch: '/demo-watch.jpg',
  headset: '/demo-headset.jpg',
  shoes: '/demo-shoes.jpg',
  backpack: '/demo-backpack.jpg',
  camera: '/demo-camera.jpg',
  skincare: '/demo-skincare.jpg',
  laptop: '/demo-laptop.jpg',
}

export const sampleProducts = [
  {
    itemId: 'DRZ-1847201',
    sku: 'AUR-EB-X7-BLK',
    title: 'AuroraSound X7 Wireless Earbuds with ANC and 42H Case',
    query: 'wireless earbuds',
    price: 5290,
    cost: 3475,
    stock: 184,
    rating: 4.7,
    reviewCount: 1284,
    imageCount: 7,
    imageUrl: sampleImages.earbuds,
    source: 'Sample catalog',
  },
  {
    itemId: 'DRZ-1847202',
    sku: 'NOVA-FIT-S2-GRY',
    title: 'NovaFit S2 Bluetooth Calling Smart Watch',
    query: 'smartwatch',
    price: 6990,
    cost: 4550,
    stock: 96,
    rating: 4.6,
    reviewCount: 842,
    imageCount: 8,
    imageUrl: sampleImages.watch,
    source: 'Sample catalog',
  },
  {
    itemId: 'DRZ-1847203',
    sku: 'SONIC-HS-G9',
    title: 'SonicWave G9 Gaming Headset with Noise Cancel Mic',
    query: 'gaming headset',
    price: 4190,
    cost: 2680,
    stock: 142,
    rating: 4.5,
    reviewCount: 613,
    imageCount: 6,
    imageUrl: sampleImages.headset,
    source: 'Sample catalog',
  },
  {
    itemId: 'DRZ-1847204',
    sku: 'STRIDE-RN-41',
    title: 'StrideFlex Lightweight Running Shoes for Men',
    query: 'running shoes',
    price: 3590,
    cost: 2210,
    stock: 211,
    rating: 4.4,
    reviewCount: 932,
    imageCount: 9,
    imageUrl: sampleImages.shoes,
    source: 'Sample catalog',
  },
  {
    itemId: 'DRZ-1847205',
    sku: 'URBAN-BP-18L',
    title: 'UrbanCarry 18L Water Resistant Laptop Backpack',
    query: 'laptop backpack',
    price: 2990,
    cost: 1815,
    stock: 258,
    rating: 4.6,
    reviewCount: 1087,
    imageCount: 7,
    imageUrl: sampleImages.backpack,
    source: 'Sample catalog',
  },
  {
    itemId: 'DRZ-1847206',
    sku: 'PIXEL-MINI-CAM',
    title: 'PixelMini 1080p Vlogging Camera Kit',
    query: 'vlogging camera',
    price: 12990,
    cost: 9050,
    stock: 47,
    rating: 4.3,
    reviewCount: 274,
    imageCount: 8,
    imageUrl: sampleImages.camera,
    source: 'Sample catalog',
  },
  {
    itemId: 'DRZ-1847207',
    sku: 'GLOW-SERUM-C',
    title: 'GlowNest Vitamin C Serum 30ml',
    query: 'vitamin c serum',
    price: 1690,
    cost: 930,
    stock: 319,
    rating: 4.8,
    reviewCount: 1516,
    imageCount: 6,
    imageUrl: sampleImages.skincare,
    source: 'Sample catalog',
  },
  {
    itemId: 'DRZ-1847208',
    sku: 'PRODOCK-USBC-7',
    title: 'ProDock 7-in-1 USB-C Hub for Laptop',
    query: 'usb c hub',
    price: 4490,
    cost: 2860,
    stock: 118,
    rating: 4.5,
    reviewCount: 689,
    imageCount: 6,
    imageUrl: sampleImages.laptop,
    source: 'Sample catalog',
  },
]

export const sampleCompetitorProducts = [
  {
    rank: 1,
    itemId: 'MKT-WIRELESS-EARBUDS-01',
    title: 'Prime Wireless Earbuds 1',
    productUrl: 'https://www.daraz.pk/catalog/?q=wireless+earbuds',
    imageUrl: sampleImages.earbuds,
    price: 3810,
    currency: 'PKR',
    discountPercent: 8,
    soldCount: 259,
    reviewCount: 74,
    rating: 4.1,
    location: 'Karachi',
    imageCount: 5,
  },
  {
    rank: 2,
    itemId: 'MKT-WIRELESS-EARBUDS-02',
    title: 'Metro Wireless Earbuds 2',
    productUrl: 'https://www.daraz.pk/catalog/?q=wireless+earbuds',
    imageUrl: sampleImages.earbuds,
    price: 4290,
    currency: 'PKR',
    discountPercent: 12,
    soldCount: 285,
    reviewCount: 103,
    rating: 4.2,
    location: 'Lahore',
    imageCount: 6,
  },
  {
    rank: 3,
    itemId: 'MKT-WIRELESS-EARBUDS-03',
    title: 'Value Wireless Earbuds 3',
    productUrl: 'https://www.daraz.pk/catalog/?q=wireless+earbuds',
    imageUrl: sampleImages.earbuds,
    price: 4660,
    currency: 'PKR',
    discountPercent: 15,
    soldCount: 311,
    reviewCount: 132,
    rating: 4.4,
    location: 'Islamabad',
    imageCount: 7,
  },
  {
    rank: 4,
    itemId: 'MKT-WIRELESS-EARBUDS-04',
    title: 'Elite Wireless Earbuds 4',
    productUrl: 'https://www.daraz.pk/catalog/?q=wireless+earbuds',
    imageUrl: sampleImages.earbuds,
    price: 4970,
    currency: 'PKR',
    discountPercent: 19,
    soldCount: 337,
    reviewCount: 161,
    rating: 4.5,
    location: 'Faisalabad',
    imageCount: 8,
  },
  {
    rank: 5,
    itemId: 'MKT-WIRELESS-EARBUDS-05',
    title: 'Swift Wireless Earbuds 5',
    productUrl: 'https://www.daraz.pk/catalog/?q=wireless+earbuds',
    imageUrl: sampleImages.earbuds,
    price: 5190,
    currency: 'PKR',
    discountPercent: 22,
    soldCount: 363,
    reviewCount: 190,
    rating: 4.7,
    location: 'Rawalpindi',
    imageCount: 5,
  },
  {
    rank: 6,
    itemId: 'MKT-WIRELESS-EARBUDS-06',
    title: 'Prime Wireless Earbuds 6',
    productUrl: 'https://www.daraz.pk/catalog/?q=wireless+earbuds',
    imageUrl: sampleImages.earbuds,
    price: 5450,
    currency: 'PKR',
    discountPercent: 25,
    soldCount: 389,
    reviewCount: 219,
    rating: 4.1,
    location: 'Karachi',
    imageCount: 6,
  },
  {
    rank: 7,
    itemId: 'MKT-WIRELESS-EARBUDS-07',
    title: 'Metro Wireless Earbuds 7',
    productUrl: 'https://www.daraz.pk/catalog/?q=wireless+earbuds',
    imageUrl: sampleImages.earbuds,
    price: 5710,
    currency: 'PKR',
    discountPercent: 8,
    soldCount: 415,
    reviewCount: 248,
    rating: 4.2,
    location: 'Lahore',
    imageCount: 7,
  },
  {
    rank: 8,
    itemId: 'MKT-WIRELESS-EARBUDS-08',
    title: 'Value Wireless Earbuds 8',
    productUrl: 'https://www.daraz.pk/catalog/?q=wireless+earbuds',
    imageUrl: sampleImages.earbuds,
    price: 6030,
    currency: 'PKR',
    discountPercent: 12,
    soldCount: 441,
    reviewCount: 277,
    rating: 4.4,
    location: 'Islamabad',
    imageCount: 8,
  },
  {
    rank: 9,
    itemId: 'MKT-WIRELESS-EARBUDS-09',
    title: 'Elite Wireless Earbuds 9',
    productUrl: 'https://www.daraz.pk/catalog/?q=wireless+earbuds',
    imageUrl: sampleImages.earbuds,
    price: 6350,
    currency: 'PKR',
    discountPercent: 15,
    soldCount: 467,
    reviewCount: 306,
    rating: 4.5,
    location: 'Faisalabad',
    imageCount: 5,
  },
  {
    rank: 10,
    itemId: 'MKT-WIRELESS-EARBUDS-10',
    title: 'Swift Wireless Earbuds 10',
    productUrl: 'https://www.daraz.pk/catalog/?q=wireless+earbuds',
    imageUrl: sampleImages.earbuds,
    price: 6820,
    currency: 'PKR',
    discountPercent: 19,
    soldCount: 493,
    reviewCount: 335,
    rating: 4.7,
    location: 'Rawalpindi',
    imageCount: 6,
  },
  {
    rank: 11,
    itemId: 'MKT-WIRELESS-EARBUDS-11',
    title: 'Prime Wireless Earbuds 11',
    productUrl: 'https://www.daraz.pk/catalog/?q=wireless+earbuds',
    imageUrl: sampleImages.earbuds,
    price: 7300,
    currency: 'PKR',
    discountPercent: 22,
    soldCount: 519,
    reviewCount: 364,
    rating: 4.1,
    location: 'Karachi',
    imageCount: 7,
  },
  {
    rank: 12,
    itemId: 'MKT-WIRELESS-EARBUDS-12',
    title: 'Metro Wireless Earbuds 12',
    productUrl: 'https://www.daraz.pk/catalog/?q=wireless+earbuds',
    imageUrl: sampleImages.earbuds,
    price: 8040,
    currency: 'PKR',
    discountPercent: 25,
    soldCount: 545,
    reviewCount: 393,
    rating: 4.2,
    location: 'Lahore',
    imageCount: 8,
  },
]

export const sampleCompetitors = {
  query: 'wireless earbuds',
  source: 'showcase market',
  scrapedAt: '2026-09-08T16:24:00.000Z',
  cachedUntil: '2026-09-08T22:24:00.000Z',
  metrics: {
    count: 12,
    pricedCount: 12,
    minPrice: 3810,
    p25Price: 4660,
    medianPrice: 5580,
    p75Price: 6350,
    maxPrice: 8040,
    medianSold: 402,
    medianReviews: 234,
  },
  products: sampleCompetitorProducts,
}

export const sampleStoreReview = {
  connected: true,
  showcase: true,
  metrics: {
    orders: 1190,
    revenue: 5254000,
    cancelRate: 1.2,
    returnRate: 2.4,
    sellerRating: 96.8,
    shipOnTimeRate: 94.6,
  },
  sourceSummary: {
    synced: 3,
    total: 3,
    failed: [],
    sourceLabels: ['Seller profile', 'Orders history', 'Product catalog'],
  },
  charts: {
    dailyOrders: sampleDailyOrders,
    statusBreakdown: [
      { status: 'delivered', count: 904 },
      { status: 'shipped', count: 155 },
      { status: 'pending', count: 89 },
      { status: 'returned', count: 29 },
      { status: 'cancelled', count: 13 },
    ],
  },
  recommendations: [
    {
      severity: 'high',
      title: 'Review wireless earbuds before campaign traffic increases',
      metric: 'Current price is 5,290 while market median is 5,580',
      action:
        'Lower to 4,870 only if stock stays above 120 units and margin remains above 24%.',
    },
    {
      severity: 'medium',
      title: 'Backpack inventory is carrying the weekend demand',
      metric: '194 orders with 258 units still available',
      action:
        'Keep the product visible in the next homepage slot and monitor stock daily.',
    },
    {
      severity: 'low',
      title: 'Store health is stable',
      metric: '1.2% cancellation rate and 94.6% ship-on-time rate',
      action: 'No account-risk action is needed today.',
    },
  ],
}

export const sampleProductAnalysis = {
  ownProduct: sampleProducts[0],
  computed: {
    ownPrice: 5290,
    competitorMedianPrice: 5580,
    pricePercentile: 58,
    titleLength: sampleProducts[0].title.length,
    competitorTitleMedian: 26,
    imageCount: 7,
  },
  competitors: sampleCompetitors,
  recommendations: [
    {
      severity: 'high',
      title: 'Price can move without leaving the main market band',
      metric: 'Recommended price: PKR 4,870',
      action:
        'Use the lower price for the campaign window, then review after 48 hours.',
    },
    {
      severity: 'medium',
      title: 'Listing content is stronger than the median competitor',
      metric: '7 images against a market median of 6',
      action:
        'Keep the current gallery and move the battery-life image to position two.',
    },
    {
      severity: 'low',
      title: 'Review count supports trust',
      metric: '1,284 reviews at 4.7 rating',
      action:
        'Do not rewrite the title today; price is the more important lever.',
    },
  ],
}

export const samplePriceAnalysis = {
  currentPrice: 5290,
  recommendedPrice: 4870,
  deltaPercent: -7.9,
  pricePercentile: 58,
  guardrails: {
    autonomyLevel: 'suggest_only',
    minMarginPercent: 5,
    maxDeltaPercent: 15,
  },
  competitors: sampleCompetitors,
  rationale: [
    'The current price is slightly above the fast-moving competitor cluster.',
    'A price of PKR 4,870 keeps margin positive while moving below the median.',
    'The change stays inside the 15% max-delta guardrail and should be logged before any live update.',
  ],
}

export const sampleAiBriefs = {
  store: {
    providerLabel: 'Showcase brief',
    model: 'sample-data',
    brief:
      'Executive summary\nOrders are healthy and account risk is low.\nRecommended actions\nReview the earbuds price before campaign traffic starts.\nKeep the backpack placement live because stock and order velocity are both strong.\nRisk checks\nDo not make live pricing changes outside guardrails.',
  },
  product: {
    providerLabel: 'Showcase brief',
    model: 'sample-data',
    brief:
      'Executive summary\nAuroraSound X7 is trusted by buyers and has enough stock for a controlled price test.\nRecommended actions\nTest PKR 4,870 for 48 hours.\nKeep the current title and improve only the second image slot.\nRisk checks\nStop the test if margin drops below the configured floor.',
  },
  pricing: {
    providerLabel: 'Showcase brief',
    model: 'sample-data',
    brief:
      'Pricing rationale\nPKR 4,870 is below the market median while staying within the seller guardrail.\nRecommended actions\nLog the recommendation first, then review sales velocity after two days.\nRisk checks\nDo not enable live writes until approval workflow is confirmed.',
  },
}

const demoDailyOrders = [
  18, 22, 19, 24, 21, 28, 33, 25, 29, 31, 27, 36, 34, 38, 41, 37, 44, 39, 42,
  47, 43, 50, 46, 54, 58, 53, 61, 57, 65, 68,
].map((orders, index) => {
  const date = new Date('2026-09-08T00:00:00.000Z')
  date.setDate(date.getDate() - (29 - index))
  return { date: date.toISOString().slice(0, 10), orders }
})

export const demoStatus = {
  connected: true,
  connection: {
    sellerId: 'PK-DIQ-784219',
    sellerName: 'Urban Cart Studio',
    country: 'Pakistan',
    accountPlatform: 'daraz_pk',
    connectedAt: '2026-06-08T10:30:00.000Z',
  },
  stats: {
    ordersLast30Days: 1190,
    products: 8,
    synced: 3,
    totalSources: 3,
    lastSyncedAt: '2026-09-08T16:28:00.000Z',
    revenue: 5254000,
    charts: {
      dailyOrders: demoDailyOrders,
      statusBreakdown: [
        { status: 'delivered', count: 904 },
        { status: 'shipped', count: 155 },
        { status: 'pending', count: 89 },
        { status: 'returned', count: 29 },
        { status: 'cancelled', count: 13 },
      ],
      topProducts: [
        {
          title: 'AuroraSound X7 Wireless Earbuds with ANC',
          sku: 'AUR-EB-X7-BLK',
          orders: 286,
          units: 329,
        },
        {
          title: 'GlowNest Vitamin C Serum 30ml',
          sku: 'GLOW-SERUM-C',
          orders: 238,
          units: 281,
        },
        {
          title: 'UrbanCarry 18L Laptop Backpack',
          sku: 'URBAN-BP-18L',
          orders: 194,
          units: 211,
        },
        {
          title: 'NovaFit S2 Bluetooth Calling Smart Watch',
          sku: 'NOVA-FIT-S2-GRY',
          orders: 151,
          units: 169,
        },
      ],
    },
  },
}
